language: node_js
sudo: false
dist: trusty

node_js:
  - '8'

branches:
  only:
  - master

env:
  global:
  - LOGS_DIR=/tmp/md2-build/logs

before_install:
  - npm i -g npm@^5.0.1

install:
  - npm install

before_script:
  - mkdir -p $LOGS_DIR

script:
  - bash ./scripts/ci/test-build-and-deploy.sh

before_deploy:
  - gulp build:release
  - cd dist
  - cd md2

deploy:
  provider: npm
  skip_cleanup: true
  email: pipariyadharmesh@gmail.com
  api_key:
    secure: BQmnMJ0woZsyyKfMaBluIqVJ4/k4dQaW1sfiXRd0WQ3FxJO90dodaZUZBUUG7m20eTjzb8xZBzZsIfHn+TauTJ/dnaPQmCSc2+97gt1kc3ruXbsT5eCWdlrpjgO+fcTedM0XkZT6jdmwW8ozh1RRi0P6h2Dtrs/tq1NFAd5px1BZ5HsdkK7q58UoC+99hN7kqO5zlCBXT1LjQ8vkMSfg9h+6i2fmWUSYiUY6+s07vHmV4CivIw4RQsswIBFDmA7/pb4bFpfw5238/QYaJQ52Mo8HDO0YA5bbpP9eX3uHio1289iYxQf7xbkPQr0bXpVlcBWC6VRhE6WkDzCPk+0gLKSl6CR0AvuhQC3JBw16wRMWaBVhzlsjgA+y5GyhYuHMaUgN762NrzDpicLCxH23kNqv+H0SljTLEUsNVwHgrfCL077JP/ToGexW6Pik3ZoltDSH5QyTMw19cxNBDQmK/PtqIiEL6V3CGxaIc3ZasoAkR+IlB3OKW3X0ssKibH3RLWMj/+I4612EyXfrXbvCeyvlPRaLfUvrF2VVjztE7qTN65cnSh/8RTYi5fFGxuNB/vrYe2kOIjd3Kq+dhPBqRyl/2Xipig37y1B7pdkz330JmHg/eEQgbM8XEsRqFt5N6FaatcMU/1NU6NyowZ1UTO78tqZpEJBUQILONdTL4Mo=
  on:
    branch: master
    repo: Promact/md2
    condition: "/^publish-.*$/"

cache:
  directories:
    - $HOME/.npm
